[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap = "CMtt58BcsLJvA8J8bEf7k2UygNc9i5ucrHugE2jNuThZ"
calculator = "GrJJ2GcEDzFLxBfX81x8K3BdMHqbJxUNxCCxEnTHRpS1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/k0r1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
